In [2]:
import pandas as pd
df = pd.read_csv('HR-Employee-Attrition.csv')
df.head(20)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7
10,35,No,Travel_Rarely,809,Research & Development,16,3,Medical,1,14,...,3,80,1,6,5,3,5,4,0,3
11,29,No,Travel_Rarely,153,Research & Development,15,2,Life Sciences,1,15,...,4,80,0,10,3,3,9,5,0,8
12,31,No,Travel_Rarely,670,Research & Development,26,1,Life Sciences,1,16,...,4,80,1,5,1,2,5,2,4,3
13,34,No,Travel_Rarely,1346,Research & Development,19,2,Medical,1,18,...,3,80,1,3,2,3,2,2,1,2
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
15,29,No,Travel_Rarely,1389,Research & Development,21,4,Life Sciences,1,20,...,3,80,1,10,1,3,10,9,8,8
16,32,No,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,21,...,4,80,2,7,5,2,6,2,0,5
17,22,No,Non-Travel,1123,Research & Development,16,2,Medical,1,22,...,2,80,2,1,2,2,1,0,0,0
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
19,38,No,Travel_Rarely,371,Research & Development,2,3,Life Sciences,1,24,...,3,80,0,6,3,3,3,2,1,2

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [5]:
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [7]:
df.isnull().sum()

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [29]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace('_','')
df.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager'],
      dtype='object')

In [31]:
print("Missing values:", df.isnull().sum().sum())
print("Duplicates:", df.duplicated().sum())

Missing values: 0
Duplicates: 0

In [32]:
df["attrition_flag"] = (df["attrition"] == "Yes").astype(int)
print(df.head(10))

   age attrition     businesstravel  dailyrate              department  \
0   41       Yes      Travel_Rarely       1102                   Sales
1   49        No  Travel_Frequently        279  Research & Development
2   37       Yes      Travel_Rarely       1373  Research & Development
3   33        No  Travel_Frequently       1392  Research & Development
4   27        No      Travel_Rarely        591  Research & Development
5   32        No  Travel_Frequently       1005  Research & Development
6   59        No      Travel_Rarely       1324  Research & Development
7   30        No      Travel_Rarely       1358  Research & Development
8   38        No  Travel_Frequently        216  Research & Development
9   36        No      Travel_Rarely       1299  Research & Development

   distancefromhome  education educationfield  employeecount  employeenumber  \
0                 1          2  Life Sciences              1               1
1                 8          1  Life Sciences              1               2
2                 2          2          Other              1               4
3                 3          4  Life Sciences              1               5
4                 2          1        Medical              1               7
5                 2          2  Life Sciences              1               8
6                 3          3        Medical              1              10
7                24          1  Life Sciences              1              11
8                23          3  Life Sciences              1              12
9                27          3        Medical              1              13

   ...  standardhours stockoptionlevel  totalworkingyears  \
0  ...             80                0                  8
1  ...             80                1                 10
2  ...             80                0                  7
3  ...             80                0                  8
4  ...             80                1                  6
5  ...             80                0                  8
6  ...             80                3                 12
7  ...             80                1                  1
8  ...             80                0                 10
9  ...             80                2                 17

   trainingtimeslastyear  worklifebalance yearsatcompany  yearsincurrentrole  \
0                      0                1              6                   4
1                      3                3             10                   7
2                      3                3              0                   0
3                      3                3              8                   7
4                      3                3              2                   2
5                      2                2              7                   7
6                      3                2              1                   0
7                      2                3              1                   0
8                      2                3              9                   7
9                      3                2              7                   7

  yearssincelastpromotion  yearswithcurrmanager  attrition_flag
0                       0                     5               1
1                       1                     7               0
2                       0                     0               1
3                       3                     0               0
4                       2                     2               0
5                       3                     6               0
6                       0                     0               0
7                       0                     0               0
8                       1                     8               0
9                       7                     7               0

[10 rows x 36 columns]

In [35]:
import pandas as pd
df["age_group"] = pd.cut(df["age"], bins=[17, 25, 35, 45, 55, 100],
                         labels=["18-25", "26-35", "36-45", "46-55", "56+"])
print(df[["age","age_group"]].head(10))

   age age_group
0   41     36-45
1   49     46-55
2   37     36-45
3   33     26-35
4   27     26-35
5   32     26-35
6   59       56+
7   30     26-35
8   38     36-45
9   36     36-45

In [46]:
df["income_band"] = pd.cut(df["monthlyincome"], bins=[0, 3000, 6000, 10000, 25000],
                        labels=["Low", "Medium", "High", "Very High"])
print(df[["monthlyincome", "income_band"]].head(20))

    monthlyincome income_band
0            5993      Medium
1            5130      Medium
2            2090         Low
3            2909         Low
4            3468      Medium
5            3068      Medium
6            2670         Low
7            2693         Low
8            9526        High
9            5237      Medium
10           2426         Low
11           4193      Medium
12           2911         Low
13           2661         Low
14           2028         Low
15           9980        High
16           3298      Medium
17           2935         Low
18          15427   Very High
19           3944      Medium

In [47]:
df["tenure_band"] = pd.cut(df["yearsatcompany"], bins=[-1, 2, 5, 10, 50],
                           labels=["0-2 yrs", "3-5 yrs", "6-10 yrs", "10+ yrs"])
print(df[["yearsatcompany","tenure_band"]].head(10))

   yearsatcompany tenure_band
0               6    6-10 yrs
1              10    6-10 yrs
2               0     0-2 yrs
3               8    6-10 yrs
4               2     0-2 yrs
5               7    6-10 yrs
6               1     0-2 yrs
7               1     0-2 yrs
8               9    6-10 yrs
9               7    6-10 yrs

In [48]:
print(df[["attrition", "attrition_flag", "age_group", "income_band", "tenure_band"]].head())
print("Attrition rate %:", round(df["attrition_flag"].mean() * 100, 2))

  attrition  attrition_flag age_group income_band tenure_band
0       Yes               1     36-45      Medium    6-10 yrs
1        No               0     46-55      Medium    6-10 yrs
2       Yes               1     36-45         Low     0-2 yrs
3        No               0     26-35         Low    6-10 yrs
4        No               0     26-35      Medium     0-2 yrs
Attrition rate %: 16.12

In [49]:
df.to_csv("HR_clean.csv", index=False)
print("Saved HR_clean.csv", df.shape)

Saved HR_clean.csv (1470, 39)

In [53]:
from sqlalchemy import create_engine

#step 1 = connect the postgresql
#replace placeholder with the actual details 

                 
username="postgres"
password="sayali09"
host="localhost"
port="5433"
database="hr.data"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#step 2:load the dataframe into the psql
table_name="employe"
df.to_sql(table_name, engine, if_exists="replace",index=False)

print(f"data Successfully loaded into table'{table_name}'in database'{database}'.")

data Successfully loaded into table'employe'in database'hr.data'.